### ISSUE TITLE
How to setup the following different parameters of JANUS-WebRTC-GATEWAY ?

### ISSUE THREAD

**Issue by chegmarco1989** [RSATom/janus-gateway-snap#17] opened 2022-01-27 15:40 UTC
Hi.

I would like to know how to configure the different parameters of **JANUS-WebRTC-GATEWAY** that installed using **SNAP** (`sudo snap install janus-gateway`) on Ubuntu ???

```
JANUS_SERVER_ENDPOINT=
JANUS_SERVER_ADMIN_ENDPOINT=
JANUS_ADMIN_SECRET=
JANUS_API_SECRET=
JANUS_VIDEO_ROOM_SECRET=
```

This is for setting up a project in the PHP Laravel Framework but I don’t see resources anywhere on the internet that can help me set up these various JANUS settings and connect them to my PHP web application which requires these Janus settings before working.

**Where are these different parameters located on my Linux Server ???**

Please let me know.

**Comment by RSATom** [comment] 2022-01-28 03:27
If you are using janus-gateway snap package you can find all configs in `/var/snap/janus-gateway/common/etc`

* `JANUS_SERVER_ENDPOINT`: I think here should be URL or your Janus instance (http/https/ws/wss - it depends)
* `JANUS_SERVER_ADMIN_ENDPOINT`:  Admin URL
* `JANUS_ADMIN_SECRET`: https://github.com/meetecho/janus-gateway/blob/master/conf/janus.jcfg.sample.in#L50
* `JANUS_API_SECRET`: https://github.com/meetecho/janus-gateway/blob/master/conf/janus.jcfg.sample.in#L34
* `JANUS_VIDEO_ROOM_SECRET`: https://github.com/meetecho/janus-gateway/blob/master/conf/janus.plugin.videoroom.jcfg.sample#L64

**Comment by chegmarco1989** [comment] 2022-01-28 16:59
Hello and thank you very much for the reply.

But how should I do to find these two following pieces of information to configure them because I have almost finished my configurations and these are the two that are missing for the proper functioning of my Laravel application which uses a Janus Client which must connect to a Server Janus:

```
JANUS_SERVER_ENDPOINT: I think here should be URL for your Janus instance (http/https/ws/wss - it depends)
JANUS_SERVER_ADMIN_ENDPOINT: Admin URL
```

How to find these two parameters above in order to finish my Janus Server configuration ???

**Comment by RSATom** [comment] 2022-01-29 06:50
It's up to you what exactly protocol you will use to connect Janus.  By default `http` and `ws` (websockets) available. If you want to use `https` or `wss` you have to configure TLS.

**Comment by chegmarco1989** [comment] 2022-01-29 14:15
> It's up to you what exactly protocol you will use to connect Janus. By default `http` and `ws` (websockets) are available. If you want to use `https` or `wss` you have to configure TLS.
> 
> So to get endpoint URL you should decide what protocol you will use, and find out IP or DNS name of your server.

Thank you once again for your response.

I would like to know what you think of this link:

**1 -** https://github.com/meetecho/janus-gateway/blob/953d32ae5aa25b2fa5d4e9076099b570f7367507/conf/janus.transport.http.jcfg.sample#L13 ???
**Isn't it at this level that you must first configure `JANUS_SERVER_ENDPOINT` ???**

**2 -** And this one: https://github.com/meetecho/janus-gateway/blob/953d32ae5aa25b2fa5d4e9076099b570f7367507/conf/janus.transport.http.jcfg.sample#L38 ???
**And isn't this the second level to configure `JANUS_SERVER_ADMIN_ENDPOINT` ???**

Please guide us.

**Comment by RSATom** [comment] 2022-01-29 15:32
Do you know what is [URL](https://en.wikipedia.org/wiki/URL)?

**Comment by chegmarco1989** [comment] 2022-01-29 15:37
> Do you know what is [URL](https://en.wikipedia.org/wiki/URL)?

Our URL is: https://worklx.com

**Comment by RSATom** [comment] 2022-01-30 03:49
If you have Janus installed and running on `worklx.com` domain, then you should be able to connect it with 
`http://worklx.com:8088/janus` or `ws://worklx.com:8188` (it's for `JANUS_SERVER_ENDPOINT`)

For Admin API you should enable it with [admin_http = true](https://github.com/meetecho/janus-gateway/blob/953d32ae5aa25b2fa5d4e9076099b570f7367507/conf/janus.transport.http.jcfg.sample#L40) or [admin_ws = true](https://github.com/meetecho/janus-gateway/blob/953d32ae5aa25b2fa5d4e9076099b570f7367507/conf/janus.transport.websockets.jcfg.sample#L31) and then you should be able access it with `http://worklx.com:7088/admin` or `ws://worklx.com:7188` (`JANUS_SERVER_ADMIN_ENDPOINT`)

**Comment by chegmarco1989** [comment] 2022-01-30 05:51
> If you have Janus installed and running on `worklx.com` domain, then you should be able to connect it with
> `http://worklx.com:8088/janus` or `ws://worklx.com:8188` (it's for `JANUS_SERVER_ENDPOINT`)

But the concern is that I have several sites hosted on the Linux Server (Ubuntu) that is to say on the IP address that returns this domain. So my question and/or my concern is if it's really this domain alone that should launch Janus because when I try to connect to the url `http://worklx.com:8088/janus` and to `ws://worklx.com:8188`, it returns me to a **404 error** which simply means that this link does not exist:

![WorklxJanus](https://user-images.githubusercontent.com/51763985/151688079-5c2b8a22-2fda-4db9-8fb0-b10d435ba482.png)

Yet when I try the `snap list janus-gateway` command, I get the following return:
```
root@host:~# snap list janus-gateway
Name           Version  Rev   Tracking       Publisher  Notes
janus-gateway  v0.11.6  1418  latest/stable  rsatom     -
root@host:~# 
```

And when I also enter the command `sudo lsof -i -P -n | grep janus`, I get the following return:
```
root@host:~# sudo lsof -i -P -n | grep janus
janus      725990            root    7u  IPv6  2591432      0t0  UDP *:5002 
janus      725990            root    8u  IPv6  2591433      0t0  UDP *:5004 
janus      725990            root   15u  IPv6  2591435      0t0  TCP *:8088 (LISTEN)
janus      725990            root   21u  IPv4  2591438      0t0  TCP *:8188 (LISTEN)
root@host:~# 
```

**So my question is:**
_Don't you seriously think that there is another thing that needs to be configured at this level:_ https://github.com/meetecho/janus-gateway/blob/953d32ae5aa25b2fa5d4e9076099b570f7367507/conf/janus.transport.http.jcfg.sample#L17 ???

For example, shouldn't I enable the IP address of my Ubuntu instance on which I installed Janus at this level ???

Please enlighten me as I am completely lost and helpless with Janus setup.

**Comment by RSATom** [comment] 2022-01-30 07:38
1. you should use Domain resoling to IP on which Janus is running
2. `http://worklx.com:8088/janus` is API URL and doesn't provide any HTTP pages.

**Comment by chegmarco1989** [comment] 2022-01-30 14:35
> * You should use Domain resoling to IP (or IP directly) on which Janus is running

**And how to use the resolution of my IP address of the instance on which Janus is installed ???** 
**Where should I configure it to solve this resolution ???**

**Comment by RSATom** [comment] 2022-01-31 02:24
I just want to say you should be sure URL you are using is correct.

**Comment by chegmarco1989** [comment] 2022-01-31 03:38
> I just want to say you should be sure URL you are using is correct.

Thank you for your help. One last question still related to the `JANUS_SERVER_ENDPOINT` configuration:

So what role does the commented IP address play on this line: https://github.com/meetecho/janus-gateway/blob/953d32ae5aa25b2fa5d4e9076099b570f7367507/conf/janus.transport.http.jcfg.sample#L17 ???

Shouldn't specify my own IP address at this level ???

**Comment by RSATom** [comment] 2022-01-31 04:08
no, it's only required if you have multiple IPs and want Janus listen only on one of them.

**Comment by chegmarco1989** [comment] 2022-01-31 04:33
> no, it's only required if you have multiple IPs and want Janus listen only on one of them.

But my concern remains at the level of the URL `http://worklx.com:8088/janus` which returns a **404 error**. You think that Janus should work if it is already installed on our instance even with this **404 error** which is displayed in the web browser ???

**Comment by RSATom** [comment] 2022-01-31 04:58
Again, `http://worklx.com:8088/janus` is API URL, and since browser does not send any JSON request to it - Janus returns 404. It's intended behavior. If you want try Janus demos, you have to run https://github.com/meetecho/janus-gateway/tree/master/html in some http server. For testing purposes you can use something like `python -m SimpleHTTPServer 8080` in directory with Janus demos.

**Comment by RSATom** [comment] 2022-01-31 07:39
@chegmarco1989 if you've got all required answers, please close this issue....

**Comment by chegmarco1989** [comment] 2022-01-31 16:42
All right.

**Closed** 2022-01-31 16:43 UTC
